baseURL = "https://essen.karoc.de/"
languageCode = "de-de"
title = "Projekt:Essen"
theme = "devise"
copyright = "made to ğŸ½ï¸"

[params]
  description = "Eine Rezeptesammlung"
  header_title = "Projekt:Essen"                 # Your header title
  header_subtitle = "" # Your header subtitle
  dateFormat = "2006, Jan 2"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  recent_posts = 3000

[params.seo]
  # Title Separator: - â€“ â€” Â· â€¢ * â‹† | ~ Â« Â» < >
  titleSeparator = "â€¢"

[taxonomies]
  category = "categories"
  tag = "tags"

